FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm install
RUN npm install -g vite


EXPOSE 5000

CMD ["npm", "run", "dev"]

acorn                   mkdirp
autoprefixer            nanoid
browserslist            node-which
esbuild                 parser
eslint                  rollup
jiti                    semver
js-yaml                 tsc
jsesc                   tsserver
json5                   update-browserslist-db
loose-envify            vite

acorn                   mime
atob                    mkdirp
autoprefixer            nanoid
browserslist            node-which
esbuild                 parser
eslint                  rollup
flaschenpost-normalize  semver
flaschenpost-uncork     tsc
jiti                    tsserver
js-yaml                 update-browserslist-db
jsesc                   uuid
json5                   vite
loose-envify